import "./globals.css";
import "./style.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        <div className="relative w-full h-screen overflow-hidden">
          <video
            autoPlay
            muted
            loop
            playsInline
            className="absolute top-0 left-0 w-full h-full object-cover z-[-1]"
          >
            <source src="/videos/riddleBG-2.mp4" type="video/mp4" />
            Your browser does not support the video tag.
          </video>

          {/* Overlay content */}
          <div className="flex justify-center items-center h-full">
            
            {children}
           
          </div>
        </div>
        {/* <div className="bgimage ">
          
          
        </div> */}
      </body>
    </html>
  );
}
