
import "./globals.css";
import "./style.css"
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bgimage ">
        <Navbar/>
        {children}
        </div>
      </body>
    </html>
  );
}
